FROM node:22-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml turbo.json ./
COPY pnpm-workspace.yaml ./
COPY packages ./packages

COPY apps/web ./apps/web

RUN npm i -g pnpm
RUN pnpm install
RUN pnpm run build

EXPOSE 3000

CMD [ "pnpm", "run", "start:frontend" ]