FROM node:22-alpine

WORKDIR /app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY package.json pnpm-lock.yaml turbo.json ./
COPY pnpm-workspace.yaml ./
COPY packages ./packages

COPY apps/ws-server ./apps/ws-server

RUN echo "DATABASE_URL=${DATABASE_URL}" > ./packages/db/.env

RUN npm i -g pnpm
RUN pnpm install
RUN pnpm run db:generate
RUN pnpm run build

EXPOSE 8080

CMD [ "pnpm", "run", "start:ws" ]