name: Build and Deploy HTTP Server Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the http-server code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build http-server code and push to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.http-server
          build-args: DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: ronitghoshh/cicd-http:${{ github.sha }}

      - name: Deploy http-server image to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ronitghoshh/cicd-http:${{ github.sha }}
            sudo docker stop http-server || true
            sudo docker rm http-server || true
            sudo docker run -e DATABASE_URL=${{ secrets.DATABASE_URL }} --name http-server -p 8080:8080 -d ronitghoshh/cicd-http:${{ github.sha }}
