name: Build and Deploy Websocket Server Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the ws-server code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build ws-server code and push to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws-server
          push: true
          tags: ronitghoshh/cicd-ws:${{ github.sha }}

      - name: Deploy ws-server image to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ronitghoshh/cicd-ws:${{ github.sha }}
            sudo docker stop ws-server || true
            sudo docker rm ws-server || true
            sudo docker run -d --name ws-server -p 8080:8080 ronitghoshh/cicd-ws:${{ github.sha }}
